# Generated by Django 3.2 on 2021-08-27 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(help_text='Your Profile Picture', upload_to='student_profile')),
                ('university', models.CharField(help_text='The University You Attended.', max_length=256)),
                ('highest_qualification', models.CharField(choices=[('SECONDARY', 'Secondary'), ('BACHELORS', 'Bachelors'), ('MASTERS', 'Masters'), ('P.HD', 'P.hD')], default='Bachelors', help_text='Your Highest Qualification Obtained', max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
